---
actions:
  to: kubernetes/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{artifactId}}
  name: {{artifactId}}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{artifactId}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{artifactId}}
    spec:
      containers:
      - image: {{artifactId}}:{{artifactVersion}}
        imagePullPolicy: IfNotPresent
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8sdev
          - name: MYSQL_DATABASE
            value: my_database
          - name: MYSQL_USER
            value: springuser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-password
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080




